javaApp:
  image: lta2705/java_app:1.0.3

  port: 8080
  env:
    DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres

javaDb:
  image: postgres:15-alpine
  port: 5432
  username: postgres
  password: postgres
  dbname: postgres
  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi

tcpService:
  enabled: true
  port: 9000
  targetPort: 9000
  type: LoadBalancer
#  nodePort: 30999


#PORT
#172.16.26.132:5432

Redis:
    enabled: true
    image: redis:alpine
    port: 6379
    persistence:
        enabled: true
        storageClass: ""
        size: 1Gi