apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-configmaps
data:
  application.properties: |-
    spring.datasource.url={{ .Values.javaApp.env.DATABASE_URL }}
    spring.datasource.username={{ .Values.javaApp.env.DATABASE_USERNAME }}
    spring.datasource.password={{ .Values.javaApp.env.DATABASE_PASSWORD }}
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    server.port={{ .Values.javaApp.port }}
    logging.level.root=INFO
    logging.level.org.springframework.web=DEBUG
    tcp.server.port={{ .Values.tcpService.port }}
    


