apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: {{ .Values.javaApp.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.javaApp.port }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.javaApp.env.DATABASE_URL }}"
            - name: DATABASE_USERNAME
              value: "{{ .Values.javaApp.env.DATABASE_USERNAME }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.javaApp.env.DATABASE_PASSWORD }}"
          volumeMounts:
            - name: config-volume
              mountPath: /run/src/main/resources/application.properties
              subPath: application.properties
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: springboot-configmaps
            items:
                - key: application.properties
                  path: application.properties
